# Generated by Django 4.2.1 on 2023-05-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price_per_item',
            field=models.IntegerField(default='price', verbose_name='Цена за штуку'),
        ),
    ]
